### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by bensteers** [mukhortov/HESH-WordPress-Plugin#49] opened 2017-07-28 01:49 UTC
I'm getting this error on both the theme and plugin editor screens. The plugin is working great in the page editors, though! I can't pinpoint the line the error is coming from because it's minified.

**Comment by arniebradfo** [comment] 2017-08-15 03:17
duplicate of #51, (#51 is a duplicate of this, actually).

will be fixed in version 2.0.2

**Closed by arniebradfo** 2017-08-15 03:17 UTC
Labels: bug, duplicate
